---
- name: Get repo name
  set_fact: 
    repo_name: "{{ resource_repository | split('/') | last | split('.git') | first }}"

- name: Install npm packages
  npm:
    ci: true
    path: "/home/{{ ansible_user }}/{{ repo_name }}"

- name: Run node app
  shell: "cd /home/{{ ansible_user }}/{{ repo_name }} && npm run start"
  async: 1000
  poll: 0

- name: Ensure app is running
  shell: ps aux | grep npm
  register: app_status

- debug: msg="{{ app_status.stdout_lines }}"
