servers = [
  { :vagrant_name => "dicoding-ws", :hostname => "dicoding-ws", :ip => "192.168.111.10", :memory => "2048" },
]

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.ssh.insert_key = false
  config.vm.synced_folder "data", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
  end

  servers.each do |conf|
    config.vm.define conf[:vagrant_name] do |node|
      node.vm.hostname = conf[:hostname]
      node.vm.network "private_network", ip: conf[:ip]
      node.vm.provider "virtualbox" do |vb|
        vb.name = conf[:vagrant_name]
        vb.memory = conf[:memory]
      end
      node.vm.provision "shell", inline: <<-SHELL
        echo hello from $HOSTNAME
        cat /vagrant_data/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
      SHELL
    end
  end  
end
